### ISSUE TITLE
Error: INSUFFICIENT_ABROAD_PRIVILEGES

### ISSUE THREAD

**Issue by chmzs** [womeimingzi11/amapGeocode#4]
Error: INSUFFICIENT_ABROAD_PRIVILEGES

**Comment by womeimingzi11** [comment]
Thanks for your report. Some others also reported this error, though I do not meet this error yet. I doubt it depends on Token. Would you mind to send your token to me? I guarantee that I won’t over use this except to debug your issue. 

Here is my address chenhan28 AT gmail DOT com

**Comment by chmzs** [comment]
Thank you, I have solved it successfully, the problem is that when using the function, the longitude and latitude parameters are filled in backwards; the example is wrong
________________________________
发件人: 我是洗衣机 ***@***.***>
发送时间: 2022年8月20日 16:31
收件人: womeimingzi11/amapGeocode ***@***.***>
抄送: chmzs ***@***.***>; Author ***@***.***>
主题: Re: [womeimingzi11/amapGeocode] Error: INSUFFICIENT_ABROAD_PRIVILEGES (Issue #4)


Thanks for your report. Some others also reported this error, though I do not meet this error yet. I doubt it depends on Token. Would you mind to send your token to me? I guarantee that I won’t over use this except to debug your issue.

Here is my address chenhan28 AT gmail DOT com

―
